import { forwardRef } from 'react';
import { CartItem } from '@/types';
import { format } from 'date-fns';

interface InvoiceTemplateProps {
  cart: CartItem[];
  subtotal: number;
  taxAmount: number;
  taxRate: number;
  discountAmount: number;
  total: number;
  expectedProfit: number;
  invoiceNumber: string;
}

const InvoiceTemplate = forwardRef<HTMLDivElement, InvoiceTemplateProps>(
  ({ cart, subtotal, taxAmount, taxRate, discountAmount, total, invoiceNumber }, ref) => {
    return (
      <div ref={ref} className="invoice-template bg-white text-black p-8 max-w-[800px] mx-auto" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
        {/* Header */}
        <div className="flex justify-between items-start mb-8 pb-6 border-b-2 border-gray-200">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <div className="h-10 w-10 rounded-lg bg-indigo-600 flex items-center justify-center">
                <span className="text-white font-bold text-lg">R</span>
              </div>
              <span className="text-2xl font-bold text-gray-900">RetailPro</span>
            </div>
            <p className="text-sm text-gray-500 mt-1">Your Business, Simplified</p>
          </div>
          <div className="text-right">
            <h2 className="text-2xl font-bold text-gray-900">INVOICE</h2>
            <p className="text-sm text-gray-500 mt-1">#{invoiceNumber}</p>
            <p className="text-sm text-gray-500">{format(new Date(), 'PPP')}</p>
            <p className="text-sm text-gray-500">{format(new Date(), 'p')}</p>
          </div>
        </div>

        {/* Items Table */}
        <table className="w-full mb-8">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="text-left py-3 text-sm font-semibold text-gray-600">#</th>
              <th className="text-left py-3 text-sm font-semibold text-gray-600">Product</th>
              <th className="text-left py-3 text-sm font-semibold text-gray-600">SKU</th>
              <th className="text-right py-3 text-sm font-semibold text-gray-600">Price</th>
              <th className="text-center py-3 text-sm font-semibold text-gray-600">Qty</th>
              <th className="text-right py-3 text-sm font-semibold text-gray-600">Amount</th>
            </tr>
          </thead>
          <tbody>
            {cart.map((item, i) => (
              <tr key={item.product.id} className="border-b border-gray-100">
                <td className="py-3 text-sm text-gray-500">{i + 1}</td>
                <td className="py-3 text-sm font-medium text-gray-900">{item.product.name}</td>
                <td className="py-3 text-sm text-gray-500">{item.product.sku}</td>
                <td className="py-3 text-sm text-right text-gray-700">${item.product.sellingPrice.toFixed(2)}</td>
                <td className="py-3 text-sm text-center text-gray-700">{item.quantity}</td>
                <td className="py-3 text-sm text-right font-medium text-gray-900">
                  ${(item.product.sellingPrice * item.quantity).toFixed(2)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Totals */}
        <div className="flex justify-end mb-8">
          <div className="w-72 space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Subtotal</span>
              <span className="text-gray-900">${subtotal.toFixed(2)}</span>
            </div>
            {discountAmount > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-red-500">Discount</span>
                <span className="text-red-500">-${discountAmount.toFixed(2)}</span>
              </div>
            )}
            <div className="flex justify-between text-sm">
              <span className="text-gray-500">Tax ({taxRate}%)</span>
              <span className="text-gray-900">${taxAmount.toFixed(2)}</span>
            </div>
            <div className="border-t-2 border-gray-900 pt-2 flex justify-between">
              <span className="text-lg font-bold text-gray-900">Total</span>
              <span className="text-lg font-bold text-gray-900">${total.toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-gray-200 pt-6 text-center">
          <p className="text-xs text-gray-400">Thank you for your business!</p>
          <p className="text-xs text-gray-400 mt-1">Generated by RetailPro • {format(new Date(), 'PPP')}</p>
        </div>
      </div>
    );
  }
);

InvoiceTemplate.displayName = 'InvoiceTemplate';
export default InvoiceTemplate;
