import { CartItem } from '@/types';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InvoicePDFOptions {
  cart: CartItem[];
  subtotal: number;
  taxAmount: number;
  taxRate: number;
  discountAmount: number;
  total: number;
  expectedProfit: number;
  invoiceNumber: string;
}

export function generateInvoicePDF(options: InvoicePDFOptions): jsPDF {
  const { cart, subtotal, taxAmount, taxRate, discountAmount, total, invoiceNumber } = options;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background
  doc.setFillColor(67, 56, 202); // indigo-600
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Logo & company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('RetailPro', 14, 22);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Your Business, Simplified', 14, 30);

  // Invoice label
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', pageWidth - 14, 22, { align: 'right' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`#${invoiceNumber}`, pageWidth - 14, 30, { align: 'right' });

  // Date info
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  const dateStr = format(new Date(), 'PPP');
  const timeStr = format(new Date(), 'p');
  doc.text(`Date: ${dateStr}`, 14, 52);
  doc.text(`Time: ${timeStr}`, 14, 58);

  // Items table
  const tableData = cart.map((item, i) => [
    String(i + 1),
    item.product.name,
    item.product.sku,
    `$${item.product.sellingPrice.toFixed(2)}`,
    String(item.quantity),
    `$${(item.product.sellingPrice * item.quantity).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 68,
    head: [['#', 'Product', 'SKU', 'Unit Price', 'Qty', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [67, 56, 202],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 245, 255],
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      3: { halign: 'right' },
      4: { halign: 'center', cellWidth: 15 },
      5: { halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  });

  // Totals section
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  const totalsX = pageWidth - 80;

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);

  let currentY = finalY;
  doc.text('Subtotal:', totalsX, currentY);
  doc.setTextColor(30, 30, 30);
  doc.text(`$${subtotal.toFixed(2)}`, pageWidth - 14, currentY, { align: 'right' });
  currentY += 7;

  if (discountAmount > 0) {
    doc.setTextColor(220, 38, 38);
    doc.text('Discount:', totalsX, currentY);
    doc.text(`-$${discountAmount.toFixed(2)}`, pageWidth - 14, currentY, { align: 'right' });
    currentY += 7;
  }

  doc.setTextColor(100, 100, 100);
  doc.text(`Tax (${taxRate}%):`, totalsX, currentY);
  doc.setTextColor(30, 30, 30);
  doc.text(`$${taxAmount.toFixed(2)}`, pageWidth - 14, currentY, { align: 'right' });
  currentY += 10;

  // Total line
  doc.setDrawColor(67, 56, 202);
  doc.setLineWidth(0.5);
  doc.line(totalsX, currentY - 3, pageWidth - 14, currentY - 3);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(67, 56, 202);
  doc.text('Total:', totalsX, currentY + 4);
  doc.text(`$${total.toFixed(2)}`, pageWidth - 14, currentY + 4, { align: 'right' });

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Thank you for your business!', pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Generated by RetailPro • ${dateStr}`, pageWidth / 2, footerY + 5, { align: 'center' });

  return doc;
}

export function downloadInvoicePDF(options: InvoicePDFOptions) {
  const doc = generateInvoicePDF(options);
  doc.save(`${options.invoiceNumber}.pdf`);
}
